"""Phase C — Safety-specific testing (Adversarial manipulation, Time decay, Moderation queue)."""

import uuid
from datetime import datetime, timedelta, timezone

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine, AsyncSession

from app.config import settings
from app.models import Base, Report, ReportCategory, ReportStatus

TEST_DB_URL = "sqlite+aiosqlite:///:memory:"

test_engine = create_async_engine(TEST_DB_URL, echo=False)
test_session = async_sessionmaker(
    test_engine, class_=AsyncSession, expire_on_commit=False
)


async def _override_get_db():
    async with test_session() as session:
        try:
            yield session
        finally:
            await session.close()


def _device_id() -> str:
    return str(uuid.uuid4())


@pytest_asyncio.fixture(autouse=True)
async def setup_db():
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)


@pytest_asyncio.fixture
async def client():
    from app.main import app
    from app.db import get_db
    from app.routers.reports import limiter

    app.dependency_overrides[get_db] = _override_get_db
    limiter.enabled = False

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac

    limiter.enabled = True
    app.dependency_overrides.clear()


# ==========================================================================
# C.1 — Adversarial Scenario: Single-source adjacent cell manipulation
# ==========================================================================

class TestC1_AdversarialSingleSourceManipulation:
    """Test adversarial pattern: 1 single device_id reports 5 adjacent grid cells
    over 5 consecutive days in the same neighborhood (e.g. T. Nagar).
    Assess if the heatmap creates a high-intensity hot spot despite coming
    from a single individual."""

    @pytest.mark.asyncio
    async def test_single_device_adjacent_cluster_heatmap_weight(self, client):
        adversary_device = _device_id()
        base_lat = 13.0418
        base_lng = 80.2341

        # Submit 1 report per day across 5 adjacent grid cells (~100m steps)
        for i in range(5):
            body = {
                "lat": base_lat + (i * 0.001),
                "lng": base_lng + (i * 0.001),
                "status": "unsafe",
                "category": "poor_lighting",
                "device_id": adversary_device,
                "note": f"Adversarial report day {i+1}",
            }
            res = await client.post("/reports", json=body)
            assert res.status_code == 201

        # Fetch heatmap
        heatmap_res = await client.get("/reports/heatmap")
        assert heatmap_res.status_code == 200
        points = heatmap_res.json()

        # Total points in cluster
        cluster_points = [
            p for p in points
            if abs(p["lat"] - base_lat) < 0.01 and abs(p["lng"] - base_lng) < 0.01
        ]
        total_cluster_weight = sum(p["weight"] for p in cluster_points)

        # Check total weight generated by 1 single device
        assert len(cluster_points) == 5
        # Return total weight for risk assessment
        print(f"Total cluster weight generated by 1 device across 5 cells: {total_cluster_weight:.2f}")


# ==========================================================================
# C.2 — Time-Decay Logic Verification
# ==========================================================================

class TestC2_TimeDecayWeights:
    """Verify weight difference between a 12-month-old report vs 1-day-old report."""

    @pytest.mark.asyncio
    async def test_time_decay_difference(self, client):
        async with test_session() as db:
            now = datetime.now(timezone.utc)

            # Report 1: 365 days ago (12 months)
            old_report = Report(
                grid_lat=13.0500,
                grid_lng=80.2500,
                status=ReportStatus.unsafe,
                category=ReportCategory.poor_lighting,
                device_id=_device_id(),
                confirmations=0,
                created_at=now - timedelta(days=365),
            )

            # Report 2: 1 day ago
            recent_report = Report(
                grid_lat=13.0600,
                grid_lng=80.2600,
                status=ReportStatus.unsafe,
                category=ReportCategory.poor_lighting,
                device_id=_device_id(),
                confirmations=0,
                created_at=now - timedelta(days=1),
            )

            db.add(old_report)
            db.add(recent_report)
            await db.commit()

        # Fetch heatmap
        heatmap_res = await client.get("/reports/heatmap")
        assert heatmap_res.status_code == 200
        points = heatmap_res.json()

        old_point = next(p for p in points if abs(p["lat"] - 13.0500) < 0.001)
        recent_point = next(p for p in points if abs(p["lat"] - 13.0600) < 0.001)

        print(f"12-month-old report weight: {old_point['weight']}")
        print(f"1-day-old report weight: {recent_point['weight']}")

        # 1-day-old report should have significantly higher weight than 12-month-old report
        assert recent_point["weight"] > old_point["weight"]
        # Old unconfirmed report should hit min decay floor (0.10)
        assert old_point["weight"] == 0.10
        # Recent report should be close to 0.98+
        assert recent_point["weight"] >= 0.95


# ==========================================================================
# C.3 — Profanity-Filter Flag-For-Review Queue Verification
# ==========================================================================

class TestC3_ProfanityFlagQueueSurfacing:
    """Confirm profanity-flagged reports surface in GET /moderation/reports."""

    @pytest.mark.asyncio
    async def test_flagged_report_surfaces_in_moderation_queue(self, client):
        async with test_session() as db:
            flagged_report = Report(
                grid_lat=13.0827,
                grid_lng=80.2707,
                status=ReportStatus.unsafe,
                category=ReportCategory.poor_lighting,
                note="bad offensive word",
                device_id=_device_id(),
                is_flagged=True,
            )
            db.add(flagged_report)
            await db.commit()
            report_id = flagged_report.id

        # Query moderation reports endpoint with admin key
        admin_key = settings.ADMIN_SECRET
        headers = {"X-Admin-Key": admin_key}

        mod_res = await client.get("/moderation/reports", headers=headers)
        assert mod_res.status_code == 200
        data = mod_res.json()

        # Confirm report appears in flagged queue
        flagged_ids = [item["id"] for item in data]
        assert report_id in flagged_ids, "Profanity-flagged report failed to surface in moderation queue!"
